# Archivo: netlify.toml (en la raíz de Dalaez/datalaria-website)

# -------------------------------------------------
# INSTRUCCIONES DE BUILD PARA HUGO (¡ESTO ES LO NUEVO!)
# -------------------------------------------------
# Esto le dice a Netlify CÓMO construir tu blog
[build]
  command = "hugo"
  publish = "public"
