# Archivo: netlify.toml (en la raíz de Dalaez/datalaria-website)

# -------------------------------------------------
# INSTRUCCIONES DE BUILD PARA HUGO (¡ESTO ES LO NUEVO!)
# -------------------------------------------------
# Esto le dice a Netlify CÓMO construir tu blog
[build]
  command = "hugo"
  publish = "public"

# -------------------------------------------------
# REGLA PARA LA APP DEL TIEMPO (Esto es lo que ya tenías)
# -------------------------------------------------

# Regla para la RUTA BASE (ej: /apps/weather o /apps/weather/)
# Esto captura la petición al "directorio" y sirve el index.html
[[rewrites]]
  from = "/apps/weather/*"
  to = "https://datalaria-app-weather.netlify.app/:splat"
  status = 200
  force = true

# Regla de respaldo por si acceden sin la barra final
[[rewrites]]
  from = "/apps/weather"
  to = "https://datalaria-app-weather.netlify.app/index.html"
  status = 200
  force = true